Repository milieuinfo/webcomponent-vl-ui-input-addon, pull requests merged in 2020-06, with the labels that each got.

#24 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-input-addon.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-input-addon.js
  test/e2e/components/vl-input-addon.js
  test/e2e/input-addon.test.js
  test/e2e/pages/vl-input-addon.page.js
  test/unit/vl-input-addon.test.html
Labels: chore

#25 Importeer sinon vanuit node_modules voor de unit testen
  package-lock.json
  package.json
Labels: bugfix

#28 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: bug

#30 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  test/docker-compose.yml
Labels: chore
